### PR TITLE
add ack-pin subcommand

### PR DESCRIPTION
**Pull request by trusch**
I had this in my git stash, wanted to push before I lose it

### CODE REVIEW

**Comment by tuommaki** [comment]
Why / when would you use this?

**Comment by trusch** [comment]
@tuommaki mainly for testing. We also have accept/decline/finish task commands, so we can have more compact tests by mocking eve. With this we can also mock sara.

Its also an integration point if at any time someone would like to put up their own workers, but I know this is a far stretch on the usefulness of those commands

**Comment by aleasims** [comment]
I couldn't find anywhere, what does it mean to "ack a pin". Maybe we could be a bit more verbose about this in help?

**Comment by trusch** [comment]
@aleasims when a worker sees a pin that is assigned to him, this is like an instruction that this worker should cache the data indicated by the on-chain Pin. This process is called "pinning" in ipfs. When the worker successfully did that, they tell the chain "hey, I successfully cache that data now, please give me the money for that". This process is called "acknowledging a pin"

**Review by tuommaki — APPROVED** [review]
Ok. Let's go with this. I'd propose to hide this from help though? Might confuse end users who are just trying to send proof requests and pin ordinary files for provers?

**Review by aleasims — APPROVED** [review]

**Pull request merged**
